### ISSUE TITLE
tls: support for session ticket resumption

### ISSUE THREAD

**Issue by morpheu** [tsuru/rpaas#27]
RpaaS should support some mechanism for Session Ticket Resumption - maybe a task for create and renew a session key only for ssl enabled instances

**Comment by bmaia** [comment]
It's important to store and retrieve these tickets securely to keep the forward secrecy property. Here are some writeups on how Twitter and Cloudflare replicate TLS session tickets:

- https://blog.twitter.com/2013/forward-secrecy-at-twitter
- https://blog.cloudflare.com/kyoto-tycoon-secure-replication/

There's a tool to test for ticket reuse on https servers: https://github.com/vincentbernat/rfc5077

If we scan www.tsuru.io, we get the following output:

![image](https://cloud.githubusercontent.com/assets/2236746/18186962/47399d08-707c-11e6-9eb8-2bf795c842b2.png)

Most SSL Session ID's are different because the load balancer is forwarding connections to different machines that doesn't share tickets. Source IP persistence would not be a good idea because it may generate unbalanced distribution.

If we scan www.twitter.com, using rfc5077-client:

![image](https://cloud.githubusercontent.com/assets/2236746/18187511/801364f2-7080-11e6-9198-da6696f2b8a6.png)

The "Reuse" column is ticked and all sessions have the same ID's, even though they have different IP's. That's the ideal solution performance-wise.

**Comment by cezarsa** [comment]
I think this could be implemented securely using a little bit of embedded lua in our nginx servers. Please tell me if this approach is sensible:

1. rpaas API servers would periodically generate a new ticket key (every 1 hour?) for each registered rpaas server;
2. For each rpaas server we would call a `/update-ticket` route with the new ticket key on its nginx server. This route would be available on the server listening on `NGINX_MANAGE_PORT` (the same used for purge and healthchecks). We need that `NGINX_MANAGE_PORT` is a tls enabled server;
3. This route would have a small lua script writing the received body to a ramfs mounted file (i.e `/ramfs/ticket.key`) and reloading nginx if necessary (I'm not sure if this is needed or if nginx always reads the key);
4. The `ssl_session_ticket_key` would point to the `/ramfs/ticket.key` written by the lua script.

I think this way we can be sure that the key is propagated securely and that it never touches the disk.

@bmaia Do you see problems with this approach?

**Comment by bmaia** [comment]
> 1 - rpaas API servers would periodically generate a new ticket key (every 1 hour?) for each registered rpaas server;

Cloudflare rotates tickets every 1 hour and Twitter does so every 12 hours. Nginx supports multiple tickets, so you can rotate one ticket and keep accepting others, like a sliding window. You should rotate tickets daily, at least (less time = better security = smaller cache).

> 2 - For each rpaas server we would call a /update-ticket route with the new ticket key. This route would be available on the server listening on NGINX_MANAGE_PORT (the same used for purge and healthchecks). We need to ensure that NGINX_MANAGE_PORT is a tls enabled server;

You need to make sure that the tls enabled server belongs to the correct server (validating certificates properly). Cloudflare uses TLS mutual authentication and if you want to do that you would need a client certificate as well: the server would only serve tickets to authorized clients. Another (less secure) way to ensure that is by restricting access to the NGINX_MANAGE_PORT using ACLs.

Anyway, you need to make sure that these tickets are retrieved/distributed using Diffie-Hellman key exchange so the traffic is forward secret.

> 3 - This route would have a small lua script writing the received body to a ramfs mounted file (i.e /ramfs/ticket.key) and reloading nginx if necessary (I'm not sure if this is needed or if nginx always reads the key);

You need to reload standard nginx every time you change keys. Cloudflare included "TLS lazy loading" to their openresty nginx modules so you don’t need to modify any configuration, nor reload the server when you change keys. Check these references for more details:

- http://pt.slideshare.net/zilin11/zi-nginx-conf2015
- https://litespeed.io/dynamic-tls-certificates-with-openresty-and-ssl_certificate_by_lua/

> 4 - The ssl_session_ticket_key would point to the /ramfs/ticket.key written by the lua script.

It's very important to delete/replace older keys so you won't lose the "Forward Secrecy" property.
